name: "Action"
description: "Metadata for github actions"
runs:
  using: "docker"
  image: "../Dockerfile"  # there is no way to set context here so I just move devcontainer Dockerfile to the project root dir