# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# ! doesn't include pytest/coveragepy
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace       # ? trims trailing whitespace
        exclude: (imgs|.devcontainer)/.*
    -   id: end-of-file-fixer         # ? ensures that a file is either empty, or ends with one newline
        exclude: (imgs|.devcontainer)/.*
    -   id: check-yaml                # ? checks yaml files for parseable syntax
    -   id: check-added-large-files   # ? check-added-large-files
    -   id: check-toml                # ? checks toml files for parseable syntax
    -   id: requirements-txt-fixer    # ? sorts entries in requirements.txt
    -   id: detect-private-key        # ? detects the presence of private keys

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        files: src/

-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        files: src/
        args: [--statistics, --tee, --output-file=flake8stats.txt]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        files: src/
        additional_dependencies: [types-PyYAML==6.0.12.11]
