
repos:
  - repo: builtin
    hooks:
    - id: trailing-whitespace       # ? trims trailing whitespace
    - id: end-of-file-fixer         # ? ensures that a file is either empty, or ends with one newline
    - id: check-yaml                # ? checks yaml files for parseable syntax
    - id: check-added-large-files   # ? check-added-large-files
    - id: check-toml                # ? checks toml files for parseable syntax
    - id: detect-private-key        # ? detects the presence of private keys

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      # run linter + fix if possible
      - id: ruff-check
        args: [ --fix ]
      # Run formatter
      - id: ruff-format

  # run ty via local repo, there are no pre-commit hooks for ty yet
  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: uvx ty check
        language: system
        types: [python]
        require_serial: true
        exclude: tests        # verify why exclude doesn't come from pyproject.toml config

  - repo: https://github.com/PyCQA/bandit
    rev: '1.9.2'
    hooks:
      - id: bandit
        name: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        args: ["-c", "pyproject.toml", "-r", "./pic_back/"]
        language: python
        language_version: python3
        types: [python]
        require_serial: true
        additional_dependencies: ["bandit[toml]"]
