version: '3.8'

services:
  app-name:
    volumes:
      - ..:/workspace
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    tty: true   # * will keep container running so we can execute commands on it -- this is needed for testing in pipeline
    container_name: app-name-container
