name: checks

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**'
      - 'pic_back/**'
      - 'caddy/**'
      - '**/Dockerfile'
      - '.python-version'

jobs:
  # every branch
  checks:
    env:
      EXECUTE_IN_CONTAINER: docker run --env-file ./tests/.env.test pyplate-test-image:latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Build docker test image
        run: docker build -f ./.github/workflows/Dockerfile . --tag pyplate-test-image

      - name: Run static checks via prek
        run:  $EXECUTE_IN_CONTAINER uv run prek run --all-files

      - name: Run unit tests
        run: $EXECUTE_IN_CONTAINER uv run pytest --cov=pyplate
