name: checks

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Move Dockerfile from devcontainer
      run: mv ./.devcontainer/Dockerfile ./Dockerfile

    - name: Set docker image from devcontainer
      uses: ./.github/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt

    - name: Run pre-commit related checks
      run: pre-commit run --all-files

    - name: Test with PyTest
      run: coverage run -m pytest ./src/

    - name: Check coverage with coverage.py
      run: coverage report -m

    - name: Generate xml report
      run: coverage xml

    - name: Create coverage badge and add to repo
      run: |
        genbadge coverage --input-file=coverage.xml --output-file=imgs/badges/coverage.svg
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add imgs/badges/coverage.svg
        git commit -m "Update coverage badge" || echo "No changes to commit"
        git push
