name: checks

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Move Dockerfile from devcontainer
      run: mv ./.devcontainer/Dockerfile ./Dockerfile

    - name: Set docker image from devcontainer
      uses: ./.github/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt

    - name: Check typing with mypy
      run: mypy ./src/

    - name: Format with Black
      run: black ./src/

    - name: Lint with flake8
      run: flake8 ./src/

    - name: Test with PyTest
      run: pytest ./src/tests/
